
obj-y += CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cec.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp_ex.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.o
obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.o
# obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o
# obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.o
# obj-y += STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.o
